name: horizontal_weekly_calendar
description: This is a simple horizontal weekly customizable calendar
version: 1.0.0
homepage: https://github.com/AhmedZaeem/horizontal_weekly_calendar

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:


